---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/7/15 10:26
---

function GUIUtility_CreateRequestIcon(techId, offset, teamType)
    local techIcon = GetGUIManager():CreateGraphicItem()
    techIcon:SetTexture("ui/buildmenu.dds")
    techIcon:SetAnchor(GUIItem.Center, GUIItem.Top)
    techIcon:SetSize(Vector(50,50,0))
    techIcon:SetIsVisible(false)
    techIcon:SetPosition(offset)
    techIcon:SetTexturePixelCoordinates(GUIUnpackCoords(GetTextureCoordinatesForIcon(techId)))
    techIcon:SetColor(kIconColors[teamType])
    return techIcon
end