---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by letsb.
--- DateTime: 2026/2/19 1:36
---

function Alien:GetPlayerScale()
    return Player.GetPlayerScale(self) * self:GetCondensedScale()
end 

function Alien:GetCondensedScale()
    local hasCondense = self:GetHasUpgrade(kTechId.Condense)
    if hasCondense then
        return 1 - 0.08 * self:GetSpurLevel()
    end
    
    return 1
end